# -*- coding: utf-8 -*-
CARDS=[
 dict(id=10427,cat="东方艺术",t="忍冈之月",a="月冈芳年",y="1888",cr="Tsukioka Yoshitoshi / Public domain",
  bg="《月百姿》之一,一名女子在月下持笠而行。",
  how="大片留白只衬一个身影,月只是淡淡一圈。",
  why="《月百姿》一百幅,是浮世绘最后的高峰。",
  more="现藏日本。"),
 dict(id=10428,cat="东方艺术",t="看影的女子",a="月冈芳年",y="1892",cr="Tsukioka Yoshitoshi / Public domain",
  bg="女子看着自己投在纸门上的影子。",
  how="影是墨的一块,人是线的一组,两者并置。",
  why="他画完这批的次年就发疯去世,五十三岁。",
  more="现藏日本。"),
 dict(id=10429,cat="东方艺术",t="女子斩勘助",a="月冈芳年",y="1866",cr="Tsukioka Yoshitoshi / Public domain",
  bg="《英名二十八众句》之一,血腥题材的锦绘。",
  how="血用红色胶质厚印,凸出纸面。",
  why="幕末动乱时最卖钱的就是这类「无残绘」。",
  more="现藏日本。"),
 dict(id=10430,cat="东方艺术",t="夕颜之幽灵",a="月冈芳年",y="1885",cr="Tsukioka Yoshitoshi / Public domain",
  bg="《源氏物语》里夕颜的鬼魂,缠在瓠花的藤上。",
  how="幽灵没有脚,身体渐渐化进花藤。",
  why="他画鬼,靠的是把形一点点抹掉。",
  more="现藏日本。"),
 dict(id=10431,cat="东方艺术",t="斋藤鬼若丸骑鲤",a="月冈芳年",y="1873",cr="Tsukioka Yoshitoshi / Public domain",
  bg="少年武藏坊弁庆(幼名鬼若丸)擒住巨鲤。",
  how="鲤鱼的鳞片逐片印出,红黑对比强烈。",
  why="他是歌川国芳的学生——那条鲤鱼的画法就是国芳教的。",
  more="现藏日本。"),
 dict(id=10432,cat="东方艺术",t="东方朔与三浦大助",a="月冈芳年",y="1873",cr="Tsukioka Yoshitoshi / Public domain",
  bg="传说中的长寿者们同框:汉代的东方朔与镰仓的三浦大助。",
  how="红底上人物密集,姿态夸张。",
  why="明治初年的锦绘,中日的典故还常常混着用。",
  more="现藏日本。"),
 dict(id=10433,cat="东方艺术",t="浴后的女子",a="桥口五叶",y="1915",cr="Hashiguchi Goyō / Public domain",
  bg="沐浴后的女子蹲着擦身。",
  how="肌肤用无色的空押压出凹凸,不着一笔颜色。",
  why="他一生只做了十四幅版画——每一幅都亲自监督到最后一版。",
  more="现藏日本。"),
 dict(id=10434,cat="东方艺术",t="梳发的女子",a="桥口五叶",y="1920",cr="Hashiguchi Goyō / Public domain",
  bg="女子低头梳理长发。",
  how="发丝一根根刻出,背景撒了云母粉。",
  why="他是「新版画」运动最讲究的一位,四十一岁病逝。",
  more="现藏日本。"),
 dict(id=10435,cat="东方艺术",t="化妆的女子",a="桥口五叶",y="1918",cr="Hashiguchi Goyō / Public domain",
  bg="女子对镜施粉。",
  how="镜中与镜外两张脸,神情不同。",
  why="他做版画之前是夏目漱石小说的封面设计师。",
  more="现藏日本。"),
 dict(id=10436,cat="东方艺术",t="浴后·另本",a="桥口五叶",y="1920",cr="Hashiguchi Goyō / Public domain",
  bg="同题材的另一幅,女子背对观者。",
  how="背部的肌理靠纸的压痕表现。",
  why="他去世后,母亲与弟弟继续印他留下的版。",
  more="现藏日本。"),
 dict(id=10437,cat="东方艺术",t="夏衣的女子",a="桥口五叶",y="1920",cr="Hashiguchi Goyō / Public domain",
  bg="穿夏日单衣的女子端坐。",
  how="薄衣的透明感靠多层浅色叠印。",
  why="他要求刻工按他的线一分不差地刻——成本高到没人能学。",
  more="现藏日本。"),
 dict(id=10438,cat="东方艺术",t="温泉宿",a="桥口五叶",y="1920",cr="Hashiguchi Goyō / Public domain",
  bg="温泉旅馆里的女子。",
  how="和服的花纹与背景的绿被处理成同一层。",
  why="这是他生前完成的最后几幅之一。",
  more="现藏日本。"),
 dict(id=10440,cat="东方艺术",t="无我",a="横山大观",y="1897",cr="Yokoyama Taikan / Public domain",
  bg="一个孩子立在树下,双手拢在袖中,神情空茫。",
  how="用色极淡,轮廓被有意模糊——这就是「朦胧体」。",
  why="当时的评论骂它「没有线条就不是日本画」,他扛了下来。",
  more="重要文化财,现藏东京国立博物馆。"),
 dict(id=10441,cat="东方艺术",t="相马旧王城",a="歌川国芳",y="1844",cr="Utagawa Kuniyoshi / Public domain",
  bg="妖术师泷夜叉姬召出巨大的骷髅。",
  how="骷髅横跨三张纸,骨骼的画法参考了西洋解剖图。",
  why="浮世绘史上最有名的一具骷髅——它比恐怖片早了一百年。",
  more="现藏日本。"),
 dict(id=10442,cat="东方艺术",t="牛若丸习剑",a="歌川国芳",y="1851",cr="Utagawa Kuniyoshi / Public domain",
  bg="少年源义经(牛若丸)向天狗学剑。",
  how="人物动势剧烈,构图对角线切开。",
  why="他是画武者绘的第一号人物——动作永远在最紧的一刻。",
  more="现藏日本。"),
 dict(id=10443,cat="东方艺术",t="风景与美人",a="歌川国芳",y="江户",cr="Utagawa Kuniyoshi / Public domain",
  bg="美人像与背后的风景并置。",
  how="人物用大块的和服花纹填满,风景反而收小。",
  why="幕府禁止画歌舞伎与游女,画师只好绕着走。",
  more="现藏日本。"),
 dict(id=10444,cat="东方艺术",t="水浒传百八好汉",a="歌川国芳",y="1830s",cr="Utagawa Kuniyoshi / Public domain",
  bg="《水浒传》的梁山好汉,他画了七十多幅。",
  how="满身刺青,肌肉贲张,姿态夸张到失真。",
  why="这套画在江户掀起了刺青热——真有人照着纹身。",
  more="现藏日本。"),
 dict(id=10445,cat="东方艺术",t="笛",a="歌川国芳",y="约1855",cr="Utagawa Kuniyoshi / Public domain",
  bg="夜里吹笛的人物。",
  how="蓝色为主调,普鲁士蓝当时刚从荷兰传入。",
  why="那一抹「广重蓝」,其实是舶来的化学颜料。",
  more="现藏日本。"),
 dict(id=10446,cat="东方艺术",t="玉取海女",a="歌川国芳",y="1844",cr="Utagawa Kuniyoshi / Public domain",
  bg="传说中的海女从龙宫夺回宝珠,被章鱼与鱼群追赶。",
  how="水下的动势用衣带与发丝的飘拂交代。",
  why="他画水的本事,是从西洋铜版画里偷学的。",
  more="现藏日本。"),
 dict(id=10447,cat="东方艺术",t="山姥与金太郎",a="河锅晓斋",y="约1850s",cr="Kawanabe Kyōsai / Public domain",
  bg="传说中的山中老妪与她养大的怪力儿童。",
  how="线条粗放,人物比例失常,故意画得野。",
  why="他七岁拜国芳为师,九岁在河里捞到人头拿回家写生。",
  more="现藏日本。"),
 dict(id=10448,cat="东方艺术",t="杨贵妃理妆",a="河锅晓斋",y="约1850s",cr="Kawanabe Kyōsai / Public domain",
  bg="唐玄宗的宠妃在梳妆。",
  how="衣纹繁复,面容却被画得略带滑稽。",
  why="他什么都画:佛画、春画、政治漫画——因此坐过牢。",
  more="现藏日本。"),
 dict(id=10449,cat="东方艺术",t="戏耍的妖怪",a="河锅晓斋",y="明治",cr="Kawanabe Kyōsai / Public domain",
  bg="一群妖怪在嬉闹。",
  how="笔法迅疾,近乎速写。",
  why="他自称「画鬼」——既是画鬼怪,也是画得像着了魔。",
  more="现藏日本。"),
 dict(id=10450,cat="东方艺术",t="鸟兽戏画",a="河锅晓斋",y="约1870",cr="Kawanabe Kyōsai / Public domain",
  bg="拟人化的动物在玩闹,致敬平安时代的《鸟兽人物戏画》。",
  how="水墨速写式的用笔,不打草稿。",
  why="他常在酒宴上当众作画——喝得越多画得越快。",
  more="现藏日本。"),
 dict(id=10451,cat="东方艺术",t="画会",a="河锅晓斋",y="约1880",cr="Kawanabe Kyōsai / Public domain",
  bg="一群人围观画家现场作画的场面。",
  how="人物密集,每张脸都有表情。",
  why="英国建筑师康德尔拜他为师,后来写了本书把他介绍给西方。",
  more="现藏日本。"),
 dict(id=10452,cat="东方艺术",t="地狱太夫",a="河锅晓斋",y="约1870s",cr="Kawanabe Kyōsai / Public domain",
  bg="传说中的名妓地狱太夫,和服上绣满地狱景象。",
  how="衣上的地狱图案被逐一画出,骷髅在她身后跳舞。",
  why="他把最艳的题材与最狠的死亡缝在同一件衣服上。",
  more="现藏日本。"),
 dict(id=10453,cat="东方艺术",t="猫与梅",a="菱田春草",y="1906",cr="Hishida Shunsō / Public domain",
  bg="梅枝下的一只黑白猫。",
  how="猫毛用无数细笔叠出,背景是空的。",
  why="他与横山大观一起被骂「朦胧体」,却熬到了平反。",
  more="重要文化财,现藏日本。"),
 dict(id=10454,cat="东方艺术",t="牧童",a="菱田春草",y="明治",cr="Hishida Shunsō / Public domain",
  bg="牧童骑牛走过树下,鸟在空中。",
  how="墨色极淡,树影只是几团灰。",
  why="他三十六岁因视网膜炎失明,次年去世。",
  more="现藏日本。"),
 dict(id=10455,cat="东方艺术",t="雾中渔夫",a="菱田春草",y="明治",cr="Hishida Shunsō / Public domain",
  bg="雾里的小舟与远山。",
  how="全画只有浓淡两级墨,靠留白造雾。",
  why="「朦胧体」的本意就是:不要线,只要空气。",
  more="现藏日本。"),
 dict(id=10456,cat="东方艺术",t="紫阳花",a="菱田春草",y="1902",cr="Hishida Shunsō / Public domain",
  bg="绣球花与飞鸟。",
  how="金地上的青绿花朵,装饰性极强。",
  why="他去印度看过阿旃陀壁画——回来后色彩变了。",
  more="现藏日本。"),
 dict(id=10457,cat="东方艺术",t="水镜",a="菱田春草",y="1897",cr="Hishida Shunsō / Public domain",
  bg="天女俯身看自己在水中的倒影。",
  how="人物与倒影用同样淡的墨,几乎分不出虚实。",
  why="他二十三岁画的——那时朦胧体刚刚成形。",
  more="重要文化财,现藏日本。"),
 dict(id=10460,cat="东方艺术",t="海之幸·青木",a="青木繁",y="1907",cr="Aoki Shigeru / Public domain",
  bg="海神宫的传说场面,神与鱼在水底。",
  how="人体拉长,色调暗沉,近乎壁画。",
  why="他二十八岁在贫病中死去——身后才被追认为天才。",
  more="重要文化财,现藏日本。"),
 dict(id=10461,cat="东方艺术",t="海景·目良",a="青木繁",y="1904",cr="Aoki Shigeru / Public domain",
  bg="房总半岛目良的海岸。",
  how="浪与岩用厚涂堆出,笔触粗放。",
  why="他在那里的渔村住了一夏,画出了《海之幸》。",
  more="现藏日本。"),
 dict(id=10462,cat="东方艺术",t="天平时代",a="青木繁",y="1904",cr="Aoki Shigeru / Public domain",
  bg="奈良天平时代的宫廷女性沐浴场面。",
  how="裸体与织物的处理受欧洲学院派影响。",
  why="他想用油画重建日本的古代——那是明治画家的共同野心。",
  more="现藏日本。"),
 dict(id=10463,cat="东方艺术",t="日落的海",a="青木繁",y="1910",cr="Aoki Shigeru / Public domain",
  bg="夕阳下的海面与帆船。",
  how="金黄与紫灰的天空,笔触松散。",
  why="他最后几年流浪九州各地,靠画画换饭吃。",
  more="现藏日本。"),
 dict(id=10465,cat="东方艺术",t="享乐",a="青木繁",y="1904",cr="Aoki Shigeru / Public domain",
  bg="室内的人物与花。",
  how="色彩浓烈,人物姿态松弛。",
  why="他与恋人福田玉枝的那几年,是他最好的时期。",
  more="现藏日本。"),
]
